<?php
$error = null;
$tab = get_string('tab', 'lab-tests');
$allowedTabs = ['lab-tests', 'medicines', 'allergies', 'medicine-tags'];
if (!in_array($tab, $allowedTabs, true)) $tab = 'lab-tests';

if (request_method('POST')) {
    try {
        verify_csrf();
        $entity = post_string('entity');
        $action = post_string('action');
        if ($entity === 'lab_test') {
            $id = (int) ($_POST['lab_test_id'] ?? 0);
            if ($action === 'save') {
                $code = strtoupper(post_string('test_code'));
                $name = post_string('test_name');
                $price = (float) ($_POST['price'] ?? 0);
                $status = post_string('status','Active');
                if ($code === '' || $name === '') throw new RuntimeException('Test code and name are required.');
                if (!preg_match('/^[A-Z0-9-]{2,30}$/', $code)) throw new RuntimeException('Test code must use 2–30 letters, numbers or hyphens.');
                if ($price < 0) throw new RuntimeException('Test price cannot be negative.');
                if (!in_array($status, ['Active','Inactive'], true)) throw new RuntimeException('Invalid test status.');
                if ($id) {
                    db()->prepare('UPDATE lab_tests SET test_code=?,test_name=?,category=?,price=?,normal_range=?,preparation_instruction=?,status=? WHERE lab_test_id=?')->execute([$code,$name,nullable(post_string('category')),$price,nullable(post_string('normal_range')),nullable(post_string('preparation_instruction')),$status,$id]);
                    log_action('UPDATE','lab_tests',$id);
                } else {
                    db()->prepare('INSERT INTO lab_tests (test_code,test_name,category,price,normal_range,preparation_instruction,status) VALUES (?,?,?,?,?,?,?)')->execute([$code,$name,nullable(post_string('category')),$price,nullable(post_string('normal_range')),nullable(post_string('preparation_instruction')),$status]);
                    $id=(int)db()->lastInsertId(); log_action('CREATE','lab_tests',$id);
                }
                flash('catalog','Laboratory test saved.','success');
                redirect_to('catalogs',['tab'=>'lab-tests']);
            }
        }
        if ($entity === 'medicine') {
            $id = (int) ($_POST['medicine_id'] ?? 0);
            if ($action === 'save') {
                $generic = post_string('generic_name');
                $status = post_string('status','Active');
                if ($generic === '') throw new RuntimeException('Generic name is required.');
                if (!in_array($status, ['Active','Inactive'], true)) throw new RuntimeException('Invalid medicine status.');
                $values=[$generic,nullable(post_string('brand_name')),nullable(post_string('strength')),nullable(post_string('dosage_form')),nullable(post_string('manufacturer')),$status];
                if($id){$values[]=$id;db()->prepare('UPDATE medicines SET generic_name=?,brand_name=?,strength=?,dosage_form=?,manufacturer=?,status=? WHERE medicine_id=?')->execute($values);log_action('UPDATE','medicines',$id);}else{db()->prepare('INSERT INTO medicines (generic_name,brand_name,strength,dosage_form,manufacturer,status) VALUES (?,?,?,?,?,?)')->execute($values);$id=(int)db()->lastInsertId();log_action('CREATE','medicines',$id);}
                flash('catalog','Medicine saved.','success');redirect_to('catalogs',['tab'=>'medicines']);
            }
        }
        if ($entity === 'allergy') {
            $id=(int)($_POST['allergy_id']??0);$name=post_string('allergy_name');$status=post_string('status','Active');if($name==='')throw new RuntimeException('Allergy name is required.');if(!in_array($status,['Active','Inactive'],true))throw new RuntimeException('Invalid allergy status.');$values=[$name,nullable(post_string('allergy_type')),nullable(post_string('description')),$status];if($id){$values[]=$id;db()->prepare('UPDATE allergies SET allergy_name=?,allergy_type=?,description=?,status=? WHERE allergy_id=?')->execute($values);log_action('UPDATE','allergies',$id);}else{db()->prepare('INSERT INTO allergies (allergy_name,allergy_type,description,status) VALUES (?,?,?,?)')->execute($values);$id=(int)db()->lastInsertId();log_action('CREATE','allergies',$id);}flash('catalog','Allergy saved.','success');redirect_to('catalogs',['tab'=>'allergies']);
        }
        if ($entity === 'medicine_tag') {
            $medicineId=(int)($_POST['medicine_id']??0);$allergyId=(int)($_POST['allergy_id']??0);if($medicineId<1||$allergyId<1)throw new RuntimeException('Choose a medicine and allergy.');if($action==='save'){db()->prepare('INSERT INTO medicine_allergy_tags (medicine_id,allergy_id,warning_message) VALUES (?,?,?) ON DUPLICATE KEY UPDATE warning_message=VALUES(warning_message)')->execute([$medicineId,$allergyId,nullable(post_string('warning_message'))]);log_action('UPSERT','medicine_allergy_tags',$medicineId.'-'.$allergyId);flash('catalog','Safety tag saved.','success');}elseif($action==='delete'){db()->prepare('DELETE FROM medicine_allergy_tags WHERE medicine_id=? AND allergy_id=?')->execute([$medicineId,$allergyId]);log_action('DELETE','medicine_allergy_tags',$medicineId.'-'.$allergyId);flash('catalog','Safety tag removed.','success');}redirect_to('catalogs',['tab'=>'medicine-tags']);
        }
    } catch (Throwable $e) { $error=$e->getMessage(); }
}

$labTests=db()->query('SELECT * FROM lab_tests ORDER BY test_name')->fetchAll();
$medicines=db()->query('SELECT * FROM medicines ORDER BY generic_name,brand_name')->fetchAll();
$allergies=db()->query('SELECT * FROM allergies ORDER BY allergy_name')->fetchAll();
$tags=db()->query('SELECT mat.*,m.generic_name,m.brand_name,m.strength,a.allergy_name FROM medicine_allergy_tags mat JOIN medicines m ON m.medicine_id=mat.medicine_id JOIN allergies a ON a.allergy_id=mat.allergy_id ORDER BY m.generic_name,a.allergy_name')->fetchAll();
$editId=(int)($_GET['edit']??0);$edit=null;if($editId){$map=['lab-tests'=>['lab_tests','lab_test_id'],'medicines'=>['medicines','medicine_id'],'allergies'=>['allergies','allergy_id']];if(isset($map[$tab])){$stmt=db()->prepare('SELECT * FROM '.$map[$tab][0].' WHERE '.$map[$tab][1].'=?');$stmt->execute([$editId]);$edit=$stmt->fetch();}}
?>
<div class="page-header"><div><h2>Clinical catalogs</h2><p>Maintain laboratory tests, medicines, allergies and prescription safety links.</p></div></div>
<?php if($error):?><div class="alert alert-danger"><?=e($error)?></div><?php endif;?>
<div class="tabs"><a class="tab <?=$tab==='lab-tests'?'active':''?>" href="<?=e(route_url('catalogs',['tab'=>'lab-tests']))?>">Lab tests</a><a class="tab <?=$tab==='medicines'?'active':''?>" href="<?=e(route_url('catalogs',['tab'=>'medicines']))?>">Medicines</a><a class="tab <?=$tab==='allergies'?'active':''?>" href="<?=e(route_url('catalogs',['tab'=>'allergies']))?>">Allergies</a><a class="tab <?=$tab==='medicine-tags'?'active':''?>" href="<?=e(route_url('catalogs',['tab'=>'medicine-tags']))?>">Safety tags</a></div>
<?php if($tab==='lab-tests'):?><div class="grid grid-3"><div class="card" style="grid-column:span 2"><div class="table-wrap"><table class="data-table"><thead><tr><th>Code</th><th>Test</th><th>Category</th><th>Price</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($labTests as $r):?><tr><td class="table-title"><?=e($r['test_code'])?></td><td><?=e($r['test_name'])?></td><td><?=e($r['category']??'—')?></td><td><?=money($r['price'])?></td><td><span class="badge badge-<?=status_class($r['status'])?>"><?=e($r['status'])?></span></td><td><a class="btn btn-light btn-sm" href="<?=e(route_url('catalogs',['tab'=>'lab-tests','edit'=>$r['lab_test_id']]))?>">Edit</a></td></tr><?php endforeach;?></tbody></table></div></div><div class="card"><h3><?=$edit?'Edit test':'Add test'?></h3><form method="post"><?=csrf_field()?><input type="hidden" name="entity" value="lab_test"><input type="hidden" name="action" value="save"><input type="hidden" name="lab_test_id" value="<?=e($edit['lab_test_id']??'')?>"><div class="field"><label>Code</label><input class="input" name="test_code" value="<?=e($edit['test_code']??'')?>" required></div><div class="field"><label>Name</label><input class="input" name="test_name" value="<?=e($edit['test_name']??'')?>" required></div><div class="field"><label>Category</label><input class="input" name="category" value="<?=e($edit['category']??'')?>"></div><div class="field"><label>Price</label><input class="input" type="number" min="0" step="0.01" name="price" value="<?=e($edit['price']??0)?>"></div><div class="field"><label>Normal range</label><input class="input" name="normal_range" value="<?=e($edit['normal_range']??'')?>"></div><div class="field"><label>Preparation</label><textarea class="textarea" name="preparation_instruction"><?=e($edit['preparation_instruction']??'')?></textarea></div><div class="field"><label>Status</label><select class="select" name="status"><option>Active</option><option <?=($edit['status']??'')==='Inactive'?'selected':''?>>Inactive</option></select></div><button class="btn btn-primary btn-block">Save test</button></form></div></div><?php endif;?>
<?php if($tab==='medicines'):?><div class="grid grid-3"><div class="card" style="grid-column:span 2"><div class="table-wrap"><table class="data-table"><thead><tr><th>Generic</th><th>Brand</th><th>Strength</th><th>Form</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($medicines as $r):?><tr><td class="table-title"><?=e($r['generic_name'])?></td><td><?=e($r['brand_name']??'—')?></td><td><?=e($r['strength']??'—')?></td><td><?=e($r['dosage_form']??'—')?></td><td><span class="badge badge-<?=status_class($r['status'])?>"><?=e($r['status'])?></span></td><td><a class="btn btn-light btn-sm" href="<?=e(route_url('catalogs',['tab'=>'medicines','edit'=>$r['medicine_id']]))?>">Edit</a></td></tr><?php endforeach;?></tbody></table></div></div><div class="card"><h3><?=$edit?'Edit medicine':'Add medicine'?></h3><form method="post"><?=csrf_field()?><input type="hidden" name="entity" value="medicine"><input type="hidden" name="action" value="save"><input type="hidden" name="medicine_id" value="<?=e($edit['medicine_id']??'')?>"><?php foreach([['generic_name','Generic name',true],['brand_name','Brand name',false],['strength','Strength',false],['dosage_form','Dosage form',false],['manufacturer','Manufacturer',false]] as $f):?><div class="field"><label><?=$f[1]?></label><input class="input" name="<?=$f[0]?>" value="<?=e($edit[$f[0]]??'')?>" <?=$f[2]?'required':''?>></div><?php endforeach;?><div class="field"><label>Status</label><select class="select" name="status"><option>Active</option><option <?=($edit['status']??'')==='Inactive'?'selected':''?>>Inactive</option></select></div><button class="btn btn-primary btn-block">Save medicine</button></form></div></div><?php endif;?>
<?php if($tab==='allergies'):?><div class="grid grid-3"><div class="card" style="grid-column:span 2"><div class="table-wrap"><table class="data-table"><thead><tr><th>Allergy</th><th>Type</th><th>Description</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($allergies as $r):?><tr><td class="table-title"><?=e($r['allergy_name'])?></td><td><?=e($r['allergy_type']??'—')?></td><td><?=e($r['description']??'—')?></td><td><span class="badge badge-<?=status_class($r['status'])?>"><?=e($r['status'])?></span></td><td><a class="btn btn-light btn-sm" href="<?=e(route_url('catalogs',['tab'=>'allergies','edit'=>$r['allergy_id']]))?>">Edit</a></td></tr><?php endforeach;?></tbody></table></div></div><div class="card"><h3><?=$edit?'Edit allergy':'Add allergy'?></h3><form method="post"><?=csrf_field()?><input type="hidden" name="entity" value="allergy"><input type="hidden" name="action" value="save"><input type="hidden" name="allergy_id" value="<?=e($edit['allergy_id']??'')?>"><div class="field"><label>Name</label><input class="input" name="allergy_name" value="<?=e($edit['allergy_name']??'')?>" required></div><div class="field"><label>Type</label><input class="input" name="allergy_type" value="<?=e($edit['allergy_type']??'')?>"></div><div class="field"><label>Description</label><textarea class="textarea" name="description"><?=e($edit['description']??'')?></textarea></div><div class="field"><label>Status</label><select class="select" name="status"><option>Active</option><option <?=($edit['status']??'')==='Inactive'?'selected':''?>>Inactive</option></select></div><button class="btn btn-primary btn-block">Save allergy</button></form></div></div><?php endif;?>
<?php if($tab==='medicine-tags'):?><div class="grid grid-3"><div class="card" style="grid-column:span 2"><div class="table-wrap"><table class="data-table"><thead><tr><th>Medicine</th><th>Allergy</th><th>Warning</th><th></th></tr></thead><tbody><?php foreach($tags as $r):?><tr><td class="table-title"><?=e($r['generic_name'].' '.($r['strength']??''))?><div class="table-subtitle"><?=e($r['brand_name']??'')?></div></td><td><?=e($r['allergy_name'])?></td><td><?=e($r['warning_message']??'Potential allergy conflict')?></td><td><form method="post" onsubmit="return confirm('Remove this safety link?')"><?=csrf_field()?><input type="hidden" name="entity" value="medicine_tag"><input type="hidden" name="action" value="delete"><input type="hidden" name="medicine_id" value="<?=$r['medicine_id']?>"><input type="hidden" name="allergy_id" value="<?=$r['allergy_id']?>"><button class="btn btn-danger btn-sm">Remove</button></form></td></tr><?php endforeach;?></tbody></table></div></div><div class="card"><h3>Add safety tag</h3><form method="post"><?=csrf_field()?><input type="hidden" name="entity" value="medicine_tag"><input type="hidden" name="action" value="save"><div class="field"><label>Medicine</label><select class="select" name="medicine_id" required><option value="">Select</option><?php foreach($medicines as $m):?><option value="<?=$m['medicine_id']?>"><?=e($m['generic_name'].' '.($m['strength']??'').' — '.($m['brand_name']??''))?></option><?php endforeach;?></select></div><div class="field"><label>Allergy</label><select class="select" name="allergy_id" required><option value="">Select</option><?php foreach($allergies as $a):?><option value="<?=$a['allergy_id']?>"><?=e($a['allergy_name'])?></option><?php endforeach;?></select></div><div class="field"><label>Warning message</label><textarea class="textarea" name="warning_message"></textarea></div><button class="btn btn-primary btn-block">Save safety tag</button></form></div></div><?php endif;?>
